import os
SNOWFLAKE_ACCOUNT = os.getenv("DATAOPS_SNOWFLAKE_ACCOUNT")
SNOWFLAKE_USER = os.getenv("DATAOPS_SNOWFLAKE_USER")
SNOWFLAKE_PRIVATE_KEY = os.getenv("DATAOPS_SNOWFLAKE_PRIVATE_KEY")
SNOWFLAKE_DATABASE = os.getenv("DATAOPS_DATABASE")
SNOWFLAKE_SCHEMA = "RAW_POS"
SNOWFLAKE_WAREHOUSE = os.getenv("DATAOPS_CATALOG_SOLUTION_PREFIX") + "_DATA_APP_WH"
APP_PASSPHRASE = os.getenv("APP_PASSPHRASE")
SNOWFLAKE_PASSWORD = os.getenv("DATAOPS_SNOWFLAKE_PASSWORD")
SNOWFLAKE_ROLE = os.getenv("DATAOPS_CATALOG_SOLUTION_PREFIX") + "_DATA_APP"