import os
SNOWFLAKE_ACCOUNT = '<SNOWFLAKE_ACCOUNT>'
SNOWFLAKE_USER = 'DATA_APP_UNISTORE_DEMO'
SNOWFLAKE_ROLE = 'TASTY_BYTES_DATA_APP_UNISTORE_DEMO'
SNOWFLAKE_PRIVATE_KEY = '''<PRIVATE_KEY>'''
SNOWFLAKE_DATABASE = 'FROSTBYTE_TASTY_BYTES_APP_UNISTORE'
SNOWFLAKE_SCHEMA = 'RAW'
SNOWFLAKE_WAREHOUSE = 'TASTY_UNISTORE_APP_WH'
