service: TastyBytesCustomAPI2

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: us-west-2

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 180
    events:
      - http:
          path: /connector/setOrderDate
          method: GET
          cors: true
      - http:
          path: /connector/getInqueueOrders
          method: GET
          cors: true
      - http:
          path: /connector/getOrderHistory
          method: GET
          cors: true
      - http:
          path: /connector/getOrderDetails
          method: GET
          cors: true
      - http:
          path: /connector/updateOrderDetails
          method: GET
          cors: true
      - http:
          path: /connector/getWarehouseLocation
          method: GET
          cors: true
      - http:
          path: /connector/getReviewDetails
          method: GET
          cors: true
      - http:
          path: /connector/getReviewStats
          method: GET
          cors: true
      - http:
          path: /connector/getDriverDetails
          method: GET
          cors: true
      - http:
          path: /connector/getDailyDriverEarnings
          method: GET
          cors: true
      - http:
          path: /connector/getAllTimeDriverEarnings
          method: GET
          cors: true
      - http:
          path: /connector/getLocationsVisited
          method: GET
          cors: true
      - http:
          path: /connector/getMenuType
          method: GET
          cors: true
      - http:
          path: /connector/getMenuItems
          method: GET
          cors: true
      - http:
          path: /connector/getInventorySold
          method: GET
          cors: true
      - http:
          path: /connector/getItemChecklist
          method: GET
          cors: true
      - http:
          path: /connector/getInventoryOrder
          method: GET
          cors: true
      - http:
          path: /connector/getAllImages
          method: GET
          cors: true
      - http:
          path: /connector/updateSelectedLocation
          method: GET
          cors: true
      - http:
          path: /connector/updateItemInventory
          method: GET
          cors: true
      - http:
          path: /connector/placeInventoryOrder
          method: GET
          cors: true
      - http:
          path: /connector/getFoodWasteData
          method: GET
          cors: true
      - http:
          path: /connector/getAllFoodWasteData
          method: GET
          cors: true
      - http:
          path: /connector/getEarningsForFoodWastePeriod
          method: GET
          cors: true
      - http:
          path: /connector/getInventoryWasted
          method: GET
          cors: true
      - http:
          path: /connector/validateTruckCredentials
          method: GET
          cors: true
      - http:
          path: /connector/getAllReviews
          method: GET
          cors: true
      - http:
          path: /connector/getDriverEarnings
          method: GET
          cors: true
      - http:
          path: /connector/getCurrentInventory
          method: GET
          cors: true
      - http:
          path: /connector/getItemInventory
          method: GET
          cors: true
      - http:
          path: /connector/getSelectedLocationDetails
          method: GET
          cors: true
      - http:
          path: /connector/getSelectedLocation
          method: GET
          cors: true
      - http:
          path: /connector/getLocationRecommendations
          method: GET
          cors: true
      - http:
          path: /connector/getNotifications
          method: GET
          cors: true
      - http:
          path: /endpoints/getInqueueOrders
          method: GET
          cors: true
      - http:
          path: /endpoints/getOrderHistory
          method: GET
          cors: true
      - http:
          path: /endpoints/getOrderDetails
          method: GET
          cors: true
      - http:
          path: /endpoints/updateOrderDetails
          method: OPTIONS
          cors: true
      
plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - '!__pycache__/**'
    - '!_node_modules/**'
    - '!venv/**'

