service: TastyBytesCustomAPI2

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: us-west-2

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 180
    events:
      - http:
          path: /endpoints/getInqueueOrders
          method: GET
          cors: true
      - http:
          path: /endpoints/getOrderHistory
          method: GET
          cors: true
      - http:
          path: /endpoints/getOrderDetails
          method: GET
          cors: true
      - http:
          path: /endpoints/updateOrderDetails
          method: OPTIONS
          cors: true
      
plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - '!__pycache__/**'
    - '!_node_modules/**'
    - '!venv/**'

